/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Dominio.Publicacion;
import com.fasterxml.jackson.databind.ObjectMapper;
import eventManagers.EventManagerNotificacionConsultarPublicaciones;
import java.util.ArrayList;
import java.util.List;
import utils.Conexion;
import utils.iEventListener;

/**
 *
 * @author Fernando
 */
public class FrmFiltroEtiqueta extends javax.swing.JFrame implements iEventListener{

    private Conexion conexion;
    private String usuario;
    private EventManagerNotificacionConsultarPublicaciones eventManagerNotificacionConsultarPublicaciones;
    
    /**
     * Creates new form FrmFiltroEtiqueta
     */
    public FrmFiltroEtiqueta(Conexion conexion, String usuario, String etiqueta) {
        initComponents();
        this.conexion = conexion;
        this.usuario = usuario;
        this.eventManagerNotificacionConsultarPublicaciones = EventManagerNotificacionConsultarPublicaciones.getInstance(conexion, "notificarConsultaPublicaciones");
        this.eventManagerNotificacionConsultarPublicaciones.subscribe("notificarConsultaPublicaciones", this);
        this.conexion.enviarEventoPublicaciones("consultarPublicacionesPorEtiqueta", etiqueta, this.usuario);
    }

    private FrmFiltroEtiqueta() {
    }
    
    @Override
    public void update(String eventType, String contenido, String usuarioJson) {
        List<Publicacion> publicaciones = null;
        try
        {
            ObjectMapper objectMapper = new ObjectMapper();
            publicaciones = objectMapper.readValue(contenido, ArrayList.class);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        actualizarMuro(publicaciones);
    }
    
     public void actualizarMuro(List<Publicacion> publicaciones) {
        ObjectMapper objectMapper = new ObjectMapper();
        List<Publicacion> publicaciones2 = new ArrayList<>();
        int i = 0;
        while(i < publicaciones.size())
        {
            Publicacion publicacion = objectMapper.convertValue(publicaciones.get(i), Publicacion.class);
            publicaciones2.add(publicacion);
            i++;
        }
        panelPublicacionesPorEtiqueta.removeAll();
        MuroScrollPane muroScrollPane = new MuroScrollPane(conexion);
        panelPublicacionesPorEtiqueta.add(muroScrollPane.getMuro(publicaciones2, panelPublicacionesPorEtiqueta, usuario));
        panelPublicacionesPorEtiqueta.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPublicacionesPorEtiqueta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPublicacionesPorEtiqueta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelPublicacionesPorEtiqueta.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPublicacionesPorEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPublicacionesPorEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFiltroEtiqueta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFiltroEtiqueta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFiltroEtiqueta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFiltroEtiqueta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFiltroEtiqueta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPublicacionesPorEtiqueta;
    // End of variables declaration//GEN-END:variables
}
